export const typeConstants = {
  CREATE_USER_DATA: 'CREATE_USER_DATA',
  CREATE_USER: 'CREATE_USER',
  FETCH_CAROUSEL_DATA: 'FETCH_CAROUSEL_DATA',
  FETCH_MOVIE_DATA: 'FETCH_MOVIE_DATA',
  FETCH_SEARCH_DATA: 'FETCH_SEARCH_DATA',
  DELETE_SEARCH_DATA: 'DELETE_SEARCH_DATA',
  DELETE_MOVIE_DATA: 'DELETE_MOVIE_DATA',
};
